tasks:
  - name: Serveur npm
# on enchaîne les commandes avec |
    before: |
      npm install
      npm run build
    init: |
      export LIVERELOAD_URL="$(gp url 35729)/livereload.js?snipver=1&port=443"
      npm run replace
    command: |
      npm start

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8000
    onOpen: open-browser

vscode:
  extensions:
    - eamodio.gitlens
    - editorconfig.editorconfig
